# baseURL       = "http://example.org/"
languageCode  = "fr-FR"
title         = "Roxo | NWS portfolio starter theme"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Accueil"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "A propos de moi"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Prendre contact"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/desktop.jpg"
    heading               = "Réfléchir le monde et penser les idées!"
    tagline               = "WE WORK HARD, WE PLAY HARD"
    primary_button        = "Voir mon travail"
    primary_button_url    = "portfolio"
    secondary_button      = "Prendre contact"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "Mes derniers projets"
    subtitle  = "En utilisant mes experiences et ma créativité, je réalise vos envies"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/deskwood.jpg"
    title               = "Envie de travailler avec moi?"
    primary_button      = "Soumettre mon idée"
    primary_button_url  = "contact"
    secondary_button    = "Pas convaincu"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Seine innopolis"
      phone   = "06 70 15 ** **"
      email   = "grousseli@normandiewebschool.fr"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Plan du site"
        [[params.footer.sitemap.link]]
          name = "A propos de nous"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Mes projets"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Prendre contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Nous vous aidons:"
        description = "développer des solutions de conception<br>produire un contenu culturel précieux<br>créer une nouvelle expérience de marque"